### PR TITLE
Created profile section

### PR DESCRIPTION
**Pull request by jessefrench**
## Description
Created the profile section to use across all pages of the app.

## Related Issue
Issue #15.

## Motivation and Context
This change is required because all pages of the app need to have the profile section visible. 

## How Can This Be Tested?
To test, `git fetch origin profile-section`, then `git checkout profile-section`.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Zpcolburn** [comment]
Perfect.

**Review by Zpcolburn — APPROVED** [review]
👍

**Comment by taylorseager** [comment]
Looks good

**Review by taylorseager — APPROVED** [review]
looks good!

**Pull request merged**
